version: "3.9"

volumes:
  postgres_db_data:
    driver: local
    
services:
  backenddb:
    image: postgres
    container_name: backenddb-poc
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    networks:
      - network-name

  backend:
    build: .
    container_name: backend-poc
    command: python manage.py runserver 0.0.0.0:8001
    ports:        
      - 8001:8001
    env_file:
      - ./.env.dev      
    depends_on:
      - backenddb
    networks:
      - network-name
  
networks:
  network-name:
    name: poc
      