# Generated by Django 4.0 on 2021-12-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=512, null=True)),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
    ]
